name: Build & Push Docker image

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/dummy-app

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # commit + tag
      packages: write        # docker/login-action needs it
    steps:
    # 1 Checkout full history so tags are visible
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }

    # 2 Read latest tag → bump patch (1.0.0 → 1.0.1 …)
    - name: Detect current version
      id: cur
      run: |
        echo "tag=$(git describe --tags --abbrev=0 2>/dev/null || echo 1.0.0)" >>"$GITHUB_OUTPUT"
    - name: Bump patch
      id: bump
      uses: christian-draeger/increment-semantic-version@v2     
      with:
        current-version: ${{ steps.cur.outputs.tag }}
        version-fragment: patch
    - name: Commit & tag
      env:
        NEW: ${{ steps.bump.outputs.next-version }}
      run: |
        git tag "$NEW"
        git push origin "$NEW"                                   # uses GITHUB_TOKEN

    # 3 Sign in to Docker Hub
    - name: Docker Hub login
      uses: docker/login-action@v3                               
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}                 # create once in Hub settings

    # 4 Build + push multi-stage image
    - name: Build & push
      uses: docker/build-push-action@v5                        
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: |
          ${{ env.IMAGE_NAME }}:${{ steps.bump.outputs.next-version }}
          ${{ env.IMAGE_NAME }}:latest
